# -*- coding: utf-8 -*-
"""
Created on Sun Jan  5 15:15:59 2025

@author: emmet
"""


import numpy as np
from PIL import Image
from matplotlib import colors
import matplotlib.pyplot as plt
import cmath

I = np.array([[1, 0, 0],
              [0, 1, 0]])
COLORS = [(np.array(
    colors.to_rgb(colors.TABLEAU_COLORS[i])) * 255 // 1).astype("uint8")
    for i in ['tab:blue', 'tab:orange', 'tab:green', 'tab:red', 'tab:purple']
    ]



class ArrayFractal:
    """A class used to draw and calculate Fractals.

    Fractals can be generated by using one of the premade classes, or by
    creating a new fractal with arbitrary starting points and functions.
    Note: The majority of funtion systems don't result in fractals.

    Once created, fractals are iterated using (index.md#Fractal.iterate)

    Based on research by
    [Larry Riddle](https://larryriddle.agnesscott.org/ifs/ifs.htm)

    Attributes
    ----------
    S : np.array

        Default S0 = (0 + 0j) to (1 + 0j)
        the current points of the fractal

    func_list : list[functions]

        the functions to be applied every iteration


    Methods
    -------
    iterate(i: int)
        Applies func_list to the current points, S, and updates S to match

    plot()
        Plots the points S using matplotlib

    save_gif(iterations: int, duration: int = 1000)
    saves a gif at '__name__ _iterations.gif' with a frame duration of duration
    milliseconds

    """

    def __init__(self, S0: np.array, eq: np.array):
        """
        Parameters
        ----------
        S0 : list[complex]
            The initial points to iterate
        func_list : list[Callable]
            A list of funtions that determines the function system

        Returns
        -------
        Fractal

        """
        self._S0 = np.asarray(S0, dtype=np.float64)
        self.S = self._S0.copy()
        self.trans_list, self.prob_list = self.create_functions(eq)
        self._prob_cdf = np.cumsum(self.prob_list)
        if len(self._prob_cdf) > 0:
            self._prob_cdf[-1] = 1.0
        self.trans_used = []
        self._rng = np.random.default_rng()
        self._plot_list = [self._S0]
        self.limits = self.calculate_limits()

    @staticmethod
    def apply(data: np.ndarray, trans_matrix: np.ndarray, out: np.ndarray | None = None):
        mat = trans_matrix[:2, :2]
        offset = trans_matrix[:, 2]
        if data.ndim == 1:
            if out is None:
                out = data @ mat.T
                out += offset
                return out
            np.dot(data, mat.T, out=out)
            out += offset
            return out
        if out is None:
            out = data @ mat.T
            out += offset
            return out
        np.dot(data, mat.T, out=out)
        out += offset
        return out

    @staticmethod
    def from_imaginary(S0: list[complex], func_list: list[callable]):
        S = np.stack((np.real(S0), np.imag(S0)), axis=1).astype(np.float64, copy=False)
        eq = np.zeros((len(func_list), 6), dtype=np.float64)
        for i, func in enumerate(func_list):
            trans = np.array(([np.real(func(0))], [np.imag(func(0))]))
            rotation = func(1) - func(0)
            matrix = np.array([[np.real(rotation), -np.imag(rotation)],
                               [np.imag(rotation), np.real(rotation)]])
            e = np.append(matrix, trans)
            eq[i] = e.astype(np.float64, copy=False)
            # print(S, e)
        return ArrayFractal(S, eq)

    def create_functions(self, eq, run_prob=False):
        eq = np.asarray(eq, dtype=self._S0.dtype)
        if len(eq[0]) % 2 == 1:
            i = (len(eq[0]) - 1) // 3
            trans_list = [
                np.append(
                    e[: 2 * i].reshape((2, -1)),
                    e[-1 - i: -1].reshape(-1, 1),
                    1
                )
                for e in eq
            ]
            prob_list = eq[:, -1]
        else:
            i = len(eq[0]) // 3
            trans_list = [
                np.append(
                    e[: 2 * i].reshape((2, -1)),
                    e[-i:].reshape(-1, 1),
                    1
                )
                for e in eq
            ]
            prob_list = self.calculate_probabilities(trans_list)
        return trans_list, prob_list

    @staticmethod
    def calculate_probabilities(trans_list):
        det_list = []
        for a in trans_list:
            det = abs(np.linalg.det(a[:2, :2]))
            det_list.append(det if det != 0 else .003)
        normalize = [a / sum(det_list) for a in det_list]
        return normalize

    def calculate_limits(self):
        self.random_iterate(10_000)
        mins = np.min(self.S, axis=0)
        maxs = np.max(self.S, axis=0)
        expected_diff = max(maxs - mins) * 1.05
        diff = maxs - mins

        maxmin = np.array(
            (mins - (expected_diff - diff) / 2,
             maxs + (expected_diff - diff) / 2))
        self.reset()
        return maxmin.flatten('F')

    def get_xlim(self):
        return self.limits[:2]
    
    def get_ylim(self):
        return self.limits[2:]
    
    xlim = property(get_xlim)
    ylim = property(get_ylim)

    def reset(self):
        """
        Resets the fractal to initial conditions.

        Returns
        -------
        None.

        """
        self.S = self._S0.copy()
        self._plot_list = [self._S0]

    def segment(self, points: np.array) -> np.array:
        len_ = len(self._S0)
        lines = np.full((len(points) // len_, len_ * 2 + 2), np.nan)
        lines[:,:len_*2] = points.reshape((-1, 4))
        return lines.reshape((-1, 2))

    def deterministic_iterate(self, i: int=1) -> None:
        """maps the functions to S, reassigning S

        if used with the gif package
        clears the plot list (ensures proper gif plotting)
        appends S back to plot list

        Parameters
        ----------
        i : int
            The number of iterations to advance from the current state

        Returns
        -------
        None

        """
        self._plot_list.clear()
        S = self.S
        k = len(self.trans_list)
        for _ in range(i):
            len_ = len(S)
            next_S = np.empty((len_ * k, 2), dtype=S.dtype)
            for j, trans in enumerate(self.trans_list):
                start = j * len_
                end = start + len_
                self.apply(S, trans, out=next_S[start:end])
            S = next_S
        self.S = S
        self._plot_list.append(self.segment(S))

    def random_apply(self, point):
        r = self._rng.random()
        index = int(np.searchsorted(self._prob_cdf, r, side="right"))
        final_point = self.apply(point, self.trans_list[index])
        return final_point, index

    def random_iterate(self, n):
        burn_in = 1_000
        point = np.array([0, 0], dtype=self._S0.dtype)
        total = burn_in + n
        indices = np.searchsorted(
            self._prob_cdf,
            self._rng.random(total),
            side="right"
        )
        trans_list = self.trans_list
        for idx in indices[:burn_in]:
            point = self.apply(point, trans_list[int(idx)])

        self.S = np.empty((n, 2), dtype=self._S0.dtype)
        self.trans_used = np.empty((n,), dtype=np.intp)
        for i, idx in enumerate(indices[burn_in:]):
            point = self.apply(point, trans_list[int(idx)])
            self.S[i] = point
            self.trans_used[i] = idx

    def divided_iterate(self, i:int=1):
        """maps the functions to S, reassigning S,
        but dividing the resulting plot list by the # of functions
        to plot each one with a different color

        if used with the gif package
        clears the plot list (ensures proper gif plotting)
        appends the result of each transformation to plot list

        Parameters
        ----------
        i : int
            The number of iterations to advance from the current state

        Returns
        -------
        None

        """
        self._plot_list.clear()
        if i == 1:
            len_ = len(self.S)
            S = np.zeros((len_ * len(self.trans_list), 2))
            for i, trans in enumerate(self.trans_list):
                S[i * len_:(i + 1) * len_] = self.apply(self.S, trans)
                self._plot_list.append(S[i * len_:(i + 1) * len_])
            self.S = S.copy()
        else:
            self.deterministic_iterate(i - 1)
            self.divided_iterate(1)
            
    def translate(self, rotate: np.array, offset: np.array) -> None:
        """Translate and rotate the fractal using a matrix adding the
        translated version to the plot list

        Parameters
        ----------
        offset : complex
            The vector to use as offset
        angle : float
            The angle (in radians) to rotate

        Returns
        -------
        None

        """
        s_trans = self.apply(
            self._plot_list[0], np.append(rotate, offset, axis=1))
        self._plot_list.append(s_trans)

    def tile(self):
        pass

    def translate_in_place(self, rotate: np.array, offset: np.array) -> None:
        """
        Translates every element in _plot_list

        Parameters
        ----------
        offset : complex
            DESCRIPTION.
        angle : float
            DESCRIPTION.

        Returns
        -------
        None
            DESCRIPTION.

        """
        self._plot_list = [ self.apply(
            i, np.append(rotate, offset, axis=1)) for i in self._plot_list]

    def scale(self, scale: float) -> None:
        self._plot_list = [self.apply(i, scale*I) for i in self._plot_list]

    def make_image(self, resolution=(1080, 1080)):
        width, height = resolution
        pixels = np.zeros((height, width, 4), dtype=np.uint8)
        if len(self.S) == 0:
            return Image.fromarray(pixels, "RGBA")

        x = self.S[:, 0]
        y = self.S[:, 1]
        res = min(resolution)
        denom_x = (self.xlim[1] - self.xlim[0])
        denom_y = (self.ylim[1] - self.ylim[0])
        if denom_x == 0 or denom_y == 0:
            return Image.fromarray(pixels, "RGBA")

        pixelx = ((x - self.xlim[0]) / denom_x * res).astype(np.int32)
        pixely = ((self.ylim[1] - y) / denom_y * res).astype(np.int32)
        mask = (
            (pixelx >= 0) & (pixelx < width) &
            (pixely >= 0) & (pixely < height)
        )
        if hasattr(self, "trans_used") and len(self.trans_used) == len(self.S):
            color_idx = (self.trans_used % len(COLORS)).astype(np.intp)
            colors = np.empty((len(self.S), 4), dtype=np.uint8)
            colors[:, :3] = np.take(COLORS, color_idx, axis=0)
            colors[:, 3] = 255
            pixels[pixely[mask], pixelx[mask]] = colors[mask]
        else:
            pixels[pixely[mask], pixelx[mask]] = np.append(COLORS[0], 255)
        return Image.fromarray(pixels, "RGBA")
    
    def plot(self, autoscale=False):
        """Plots the fractal for human viewing"""
        self.tile()
        fig = plt.figure()
        self._fig = fig
        ax = fig.add_subplot(111)
        self._ax = ax
        self.plot_handle = [
            # ax.plot(np.real(s), np.imag(s), color="tab:blue") for s in self._plot_list
            ax.plot(s[:,0], s[:,1]) for s in self._plot_list
        ]
        if not autoscale:
            ax.set_xlim(self.limits[:2])
            ax.set_ylim(self.limits[2:])
        ax.set_aspect("equal")
        ax.axis("off")
        plt.show()

    def get_plot_fig(self):
        return self._fig
    
    def get_plot_ax(self):
        return self._ax
    
    plot_fig = property(get_plot_fig)
    plot_ax = property(get_plot_ax)

def main():
    from fractal import S0i, IFS_function
    test = ArrayFractal.from_imaginary(S0i, IFS_function["flowsnake"])
    test.random_iterate(1_000_000)
    test.plot()


if __name__ == "__main__":
    main()
