site_name: Fractals.jl
site_description: Julia tools for IFS fractal rendering
repo_url: https://github.com/Harts-do-hard-things/fractals
theme:
  name: material
nav:
  - Home: index.md
  - Quick Recipes: quick-recipes.md
