# -*- coding: utf-8 -*-
"""A module for viewing fractals

Basic usage:

```python
heighway = HeighwayDragon()
heighway.iterate(15) # More than 15 iterations can cause crashing
heighway.plot()
```

The fractals available are:
  - [HeighwayDragon](index.md#fractal.HeighwayDragon)
  - [TwinDragon](index.md#fractal.TwinDragon)
  - [GoldenDragon](index.md#fractal.GoldenDragon)
  - [Terdragon](index.md#fractal.Terdragon)
  - [FudgeFlake](index.md#fractal.FudgeFlake)
  - [LevyC](index.md#fractal.LevyC)
  - [LevyTapestryOutside](index.md#fractal.LevyTapestryOutside)
  - [LevyTapestryInside](index.md#fractal.LevyTapestryInside)
  - [KochFlake](index.md#fractal.KochFlake)
  - [Pentadendrite](index.md#fractal.Pentadendrite)
  - [Pentigree](index.md#fractal.Pentigree)
  - [Flowsnake](index.md#fractal.Flowsnake)
  - [GoldenFlake](index.md#fractal.GoldenFlake)
"""


# N.B. I used segment in the DragonFractal code
# All fractals requiring segmentation should use DragonFractal as parent


import cmath
import math
from typing import Callable

import matplotlib.pyplot as plt
import numpy as np
import animatplot as amp

try:
    import gif
except ModuleNotFoundError:
    gif = None


class Fractal:
    """A class used to draw and calculate Fractals.

    Fractals can be generated by using one of the premade classes, or by
    creating a new fractal with arbitrary starting points and functions.
    Note: The majority of funtion systems don't result in fractals.

    Once created, fractals are iterated using (index.md#Fractal.iterate)

    Based on research by
    [Larry Riddle](https://larryriddle.agnesscott.org/ifs/ifs.htm)

    Attributes
    ----------
    S : list[complex]

        Default S0 = (0 + 0j) to (1 + 0j)
        the current points of the fractal

    func_list : list[functions]

        the functions to be applied every iteration


    Methods
    -------
    iterate(i: int)
        Applies func_list to the current points, S, and updates S to match

    plot()
        Plots the points S using matplotlib

    save_gif(iterations: int, duration: int = 1000)
    saves a gif at '__name__ _iterations.gif' with a frame duration of duration
    milliseconds

    """

    def __init__(self, S0: list[complex], func_list: list[Callable]):
        """
        Parameters
        ----------
        S0 : list[complex]
            The initial points to iterate
        func_list : list[Callable]
            A list of funtions that determines the function system

        Returns
        -------
        Fractal

        """
        self._S0 = np.asarray(S0, dtype=np.complex128)
        self.S = self._S0.copy()
        self.func_list = func_list
        self._plot_list = [self._S0.copy()]
        self.plot_handle = []
        self._rng = np.random.default_rng()
        self._affine_coeffs = None
        self._affine_offsets = None
        self._prob_cdf = None
        self._init_affine_cache()
        self.limits = self.calculate_limits()

    def _init_affine_cache(self):
        coeffs = []
        offsets = []
        for func in self.func_list:
            z0 = func(0)
            z1 = func(1)
            z2 = func(2)
            a = z1 - z0
            b = z0
            # Validate affine form: f(z) == a*z + b
            if not np.isclose(z2, 2 * a + b, atol=1e-10):
                self._affine_coeffs = None
                self._affine_offsets = None
                self._prob_cdf = None
                return
            coeffs.append(a)
            offsets.append(b)

        self._affine_coeffs = np.asarray(coeffs, dtype=np.complex128)
        self._affine_offsets = np.asarray(offsets, dtype=np.complex128)
        weights = np.abs(self._affine_coeffs) ** 2
        if np.all(weights == 0):
            weights = np.ones_like(weights)
        probs = weights / np.sum(weights)
        self._prob_cdf = np.cumsum(probs)
        self._prob_cdf[-1] = 1.0

    def calculate_limits(self):
        # Fast path: stochastic limit estimate for affine IFS.
        if self._affine_coeffs is not None:
            burn_in = 1_000
            samples = 20_000
            point = 0.0 + 0.0j
            indices = np.searchsorted(
                self._prob_cdf,
                self._rng.random(burn_in + samples),
                side="right",
            )
            coeffs = self._affine_coeffs
            offsets = self._affine_offsets
            for idx in indices[:burn_in]:
                point = coeffs[idx] * point + offsets[idx]

            points = np.empty((samples,), dtype=np.complex128)
            for i, idx in enumerate(indices[burn_in:]):
                point = coeffs[idx] * point + offsets[idx]
                points[i] = point

            mins = np.array((np.min(np.real(points)), np.min(np.imag(points))))
            maxs = np.array((np.max(np.real(points)), np.max(np.imag(points))))
            expected_diff = np.max(maxs - mins) * 1.05
            diff = maxs - mins
            maxmin = np.array(
                (mins - (expected_diff - diff) / 2, maxs + (expected_diff - diff) / 2)
            )
            self.reset()
            return maxmin.flatten("F")

        # Fallback path: bounded deterministic expansion.
        S = self._S0.copy()
        for _ in range(8):
            next_blocks = [np.fromiter((func(z) for z in S), dtype=np.complex128, count=len(S))
                           for func in self.func_list]
            S = np.concatenate(next_blocks)
            if len(S) > 200_000:
                S = S[:: len(S) // 200_000 + 1]
        mins = np.array((np.min(np.real(S)), np.min(np.imag(S))))
        maxs = np.array((np.max(np.real(S)), np.max(np.imag(S))))
        expected_diff = np.max(maxs - mins) * 1.05
        diff = maxs - mins

        maxmin = np.array(
            (mins - (expected_diff - diff) / 2,
             maxs + (expected_diff - diff) / 2))
        self.reset()
        return maxmin.flatten('F')

    def get_xlim(self):
        return self.limits[:2]

    def get_ylim(self):
        return self.limits[2:]

    xlim = property(get_xlim)
    ylim = property(get_ylim)

    def reset(self):
        """
        Resets the fractal to initial conditions.

        Returns
        -------
        None.

        """
        self.S = self._S0.copy()
        self._plot_list = [self._S0.copy()]

    def iterate(self, i: int = 1) -> None:
        """maps the functions to S, reassigning S

        if used with the gif package
        clears the plot list (ensures proper gif plotting)
        appends S back to plot list

        Parameters
        ----------
        i : int
            The number of iterations to advance from the current state

        Returns
        -------
        None

        """
        self._plot_list.clear()
        S = self.S
        if self._affine_coeffs is not None:
            coeffs = self._affine_coeffs
            offsets = self._affine_offsets
            k = len(coeffs)
            for _ in range(i):
                n = len(S)
                next_S = np.empty((n * k,), dtype=np.complex128)
                for j in range(k):
                    start = j * n
                    end = start + n
                    next_S[start:end] = coeffs[j] * S + offsets[j]
                S = next_S
        else:
            for _ in range(i):
                blocks = [
                    np.fromiter((func(z) for z in S), dtype=np.complex128, count=len(S))
                    for func in self.func_list
                ]
                S = np.concatenate(blocks)
        self.S = S
        self._plot_list.append(S)

    def divided_iterate(self, i: int = 1):
        """maps the functions to S, reassigning S

        if used with the gif package
        clears the plot list (ensures proper gif plotting)
        appends the result of each transformation to plot list

        Parameters
        ----------
        i : int
            The number of iterations to advance from the current state

        Returns
        -------
        None

        """
        self._plot_list.clear()
        if i == 1:
            if self._affine_coeffs is not None:
                n = len(self.S)
                blocks = []
                for coeff, offset in zip(self._affine_coeffs, self._affine_offsets):
                    block = coeff * self.S + offset
                    blocks.append(block)
                    self._plot_list.append(block)
                self.S = np.concatenate(blocks)
            else:
                blocks = [
                    np.fromiter((func(z) for z in self.S), dtype=np.complex128, count=len(self.S))
                    for func in self.func_list
                ]
                self._plot_list.extend(blocks)
                self.S = np.concatenate(blocks)
        else:
            self.iterate(i - 1)
            self.divided_iterate(1)

    def translate(self, offset: complex, angle: float) -> None:
        """Translate and rotate the fractal in the complex plane

        Parameters
        ----------
        offset : complex
            The vector to use as offset
        angle : float
            The angle (in radians) to rotate

        Returns
        -------
        None

        """
        s_trans = self._plot_list[0] * cmath.exp(angle * 1j) + offset
        self._plot_list.append(s_trans)

    def tile(self):
        pass

    def translate_in_place(self, offset: complex, angle: float) -> None:
        """
        Translates every element in _plot_list

        Parameters
        ----------
        offset : complex
            DESCRIPTION.
        angle : float
            DESCRIPTION.

        Returns
        -------
        None
            DESCRIPTION.

        """
        rot = cmath.exp(angle * 1j)
        self._plot_list = [series * rot + offset for series in self._plot_list]

    def scale(self, scale: float) -> None:
        self._plot_list = [series * scale for series in self._plot_list]

    def plot(self):
        """Plots the fractal for human viewing"""
        self.tile()
        fig = plt.figure()
        self._fig = fig
        ax = fig.add_subplot(111)
        self._ax = ax
        self.plot_handle = [
            # ax.plot(np.real(s), np.imag(s), color="tab:blue")
            # for s in self._plot_list
            ax.plot(np.real(s), np.imag(s)) for s in self._plot_list
        ]
        ax.set_xlim(self.limits[:2])
        ax.set_ylim(self.limits[2:])
        ax.set_aspect("equal")
        ax.axis("off")
        plt.show()

    def get_plot_fig(self):
        return self._fig

    def get_plot_ax(self):
        return self._ax

    plot_fig = property(get_plot_fig)
    plot_ax = property(get_plot_ax)

    if gif:
        @gif.frame
        def _gif_plot(self) -> None:
            fig = plt.figure()
            ax = fig.add_subplot(111)
            ax.set_xlim(self.limits[:2])
            ax.set_ylim(self.limits[2:])
            ax.set_aspect("equal")
            ax.axis("off")
            for s in self._plot_list:
                ax.plot(np.real(s), np.imag(s), color="tab:blue")

        def save_gif(self, iterations: int, duration: int = 1000) -> None:
            """
            Create a gif with a specific duration in milliseconds

            Parameters
            ----------
            iterations : int
                the number of iterations to include
            duration : int, optional
                The time in milliseconds for the gif to run.
                The default is 1000.

            Returns
            -------
            None

            """
            self.tile()
            frames = [self._gif_plot()]
            for _ in range(iterations - 1):
                self.iterate(1)
                self.tile()
                frame = self._gif_plot()
                frames.append(frame)
            gif.save(
                frames,
                f"{type(self).__name__}_{iterations}.gif",
                duration
            )


class DragonFractal(Fractal):
    """A class used to draw and calculate Fractals
    that require nans inbetween segments

    Based loosely on research by
    [Larry Riddle](https://larryriddle.agnesscott.org/ifs/ifs.htm)
    """

    def segment(self, points: list[complex]) -> list:
        points = np.asarray(points, dtype=np.complex128)
        seg_len = len(self._S0)
        if seg_len <= 0:
            return points
        rows = len(points) // seg_len
        if rows == 0:
            return points
        trimmed = points[: rows * seg_len].reshape(rows, seg_len)
        out = np.full((rows, seg_len + 1), np.nan + 0j, dtype=np.complex128)
        out[:, :seg_len] = trimmed
        return out.reshape(-1)

    def plot(self):
        self._plot_list = [self.segment(s) for s in self._plot_list]
        super().plot()

    if gif:
        def save_gif(self, iterations: int, duration=1000):
            self._plot_list = [self.segment(s) for s in self._plot_list]
            self.tile()
            frames = [self._gif_plot()]
            for _ in range(iterations - 1):
                self.iterate(1)
                self._plot_list = [self.segment(s) for s in self._plot_list]
                self.tile()
                frame = self._gif_plot()
                frames.append(frame)
            gif.save(
                frames,
                "{0}_{1}.gif".format(type(self).__name__, iterations),
                duration
            )


class BinaryTree(DragonFractal):
    """
    Creates Binary Trees Based off of
    [Larry Riddle's Webpage]
    (https://larryriddle.agnesscott.org/ifs/pythagorean/symbinarytree.htm)

    See Documentation for [DragonFractal](index.md#fractal.DragonFractal)
    for implementation details
    and attached resource for creation Details
    """
    def __init__(self, B_r: float, theta: float):
        self.iterations = 0
        super().__init__(
            S0=[0, 1j],
            func_list=[
                lambda z: B_r * z * cmath.rect(1, theta) + 1j,
                lambda z: B_r * z * cmath.rect(1, -theta) + 1j,
            ],
        )

    def iterate(self, i: int):
        for _ in range(i):
            self._plot_list.clear()
            S_blocks = []
            for coeff, offset in zip(self._affine_coeffs, self._affine_offsets):
                block = coeff * self.S + offset
                S_blocks.append(block)
                cumulative = np.concatenate(S_blocks)
                self._plot_list.append(cumulative)
                self.iterations += 1
            self.S = np.concatenate(S_blocks)

    def reset(self):
        super().reset()
        self.iterations = 0

    def translate(self, offset: complex, angle: float):
        for j in range(self.iterations + 1):
            s_trans = self._plot_list[j] * cmath.exp(angle * 1j) + offset
            self._plot_list.append(s_trans)


class _AnimFractal(Fractal):
    """An experimental class
    TODO: Finish and document"""
    def create_block(self, X: list, Y: list) -> list:
        X.append(np.real(self.S))
        Y.append(np.imag(self.S))
        return X, Y

    def animate(self, i: int):
        x = [np.real(self._S0)]
        y = [np.imag(self._S0)]
        for _ in range(i):
            self.iterate(1)
            x, y = self.create_block(x, y)
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.set_title("Test")
        plt.axis(self.limits)
        timeline = amp.Timeline(range(i + 1), units="iter", fps=2)
        block = amp.blocks.Line(
            np.array(x, dtype=object), np.array(y, dtype=object), ax=ax
        )
        anim = amp.Animation([block], timeline)
        # anim.controls()
        anim.timeline_slider()
        # anim.save("levy2heighway", writer='ffmpeg', fps=timeline.fps)
        plt.show()


class _AnimateOverIter(DragonFractal):
    """Experimental Class
    TODO: Finish and document
    """
    # limits = -0.6, 1.6, -1.06, 0.308
    def reset(self):
        self.S = self._S0.copy()
        self._plot_list = [self._S0.copy()]

    def iterate(self, i: int, t: float) -> None:
        self._plot_list.clear()
        for _ in range(i):
            S = []
            for func in self.func_list:
                S.extend(list(map(func, self.S, [t] * len(self.S))))
            self.S = S
        self._plot_list.append(S)

    def animate(self):
        x = []
        y = []
        time = np.linspace(0, 1, 50)
        for t in time:
            self.iterate(15, t)
            x.append(np.real(self.segment(self.S)))
            y.append(np.imag(self.segment(self.S)))
            self.reset()
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.set_title("Test")
        ax.set_aspect("equal")
        ax.set_ylim([-0.35, 1.75])
        ax.set_xlim([-0.76, 2.5])
        timeline = amp.Timeline(time, fps=10)
        block = amp.blocks.Line(x, y)
        anim = amp.Animation([block], timeline)
        anim.controls()
        anim.save_gif(f"{type(self).__name__}_15")
        plt.show()


# GLOBALS
S0i = [0, 1]

# Vars used in golden dragon
PHI = (1 + math.sqrt(5)) * 0.5
R = (1 / PHI) ** (1 / PHI)
A = math.acos((1 + R ** 2 - R ** 4) * 0.5 / R)
B = math.acos((1 - R ** 2 + R ** 4) * 0.5 / R ** 2)

# Vars Used in terdragon
LAMBDA = 0.5 - 1j * 0.5 / math.sqrt(3)
LAMBDACONJ = 0.5 + 1j * 0.5 / math.sqrt(3)

# Vars used in twindragon
S0_TWIN = [0, 1, 1 - 1j]

# Vars used in Pentigree
P_r = (3 - math.sqrt(5)) * 0.5
P_a1 = cmath.rect(1, 0.2 * math.pi)
P_a2 = cmath.rect(1, 0.6 * math.pi)
P_na1 = cmath.rect(1, -0.2 * math.pi)
P_na2 = cmath.rect(1, -0.6 * math.pi)
P_angle = [P_a1, P_a2, P_na1, P_na2, P_na1, P_a1]
P_offset = np.cumsum([0, *P_angle[:-1]])


def _make_func(DRPR, vector, offset):
    return lambda z: DRPR * (vector * z + offset)


# Vars used in pentadendrite
Dr = math.sqrt((6 - math.sqrt(5)) / 31)
RA = 0.20627323391771757578747269015392
PA = 1 * math.cos(RA) + 1j * math.sin(RA)
SA = math.pi * 0.4
BA = cmath.rect(1, RA + SA)
CA = cmath.rect(1, RA - SA)
DA = cmath.rect(1, RA - 2 * SA)
STAR = np.exp(1j * np.arange(0, 361, 72) * math.pi / 180)
PENTAGON = np.cumsum(STAR)
VVectors = [PA, BA, PA, DA, CA, PA]
VOffset = np.cumsum([0, *VVectors[:-1]])

# Vars used in Flowsnake
F_A = math.asin(math.sqrt(3) / math.sqrt(7) * 0.5)
F_A1 = F_A - 2 * math.pi / 3
F_r = math.sqrt(7) ** -1
F_angles = [F_A1, F_A, F_A, F_A1, F_A, F_A + 2 * math.pi / 3, F_A]
F_vectors = [cmath.rect(1, PHI) for PHI in F_angles]

# trans_matrix = [0]
IFS_function = {}
# Plain Ole' Dragon Curve
IFS_function["flowsnake"] = [
    lambda z: F_r * (z * F_vectors[0] - F_vectors[0]),
    lambda z: F_r * (z * F_vectors[1] - F_vectors[0]),
    lambda z: F_r * (z * F_vectors[2] + F_vectors[1] - F_vectors[0]),
    lambda z: F_r * (z * F_vectors[3] + 2 * F_vectors[2] - F_vectors[0]),
    lambda z: F_r * (z * F_vectors[4] + F_vectors[3] +
                     F_vectors[2] - F_vectors[0]),
    lambda z: F_r
    * (z * F_vectors[5] - F_vectors[5] + F_vectors[3] +
       F_vectors[2] - F_vectors[0]),
    lambda z: F_r
    * (z * F_vectors[6] - F_vectors[5] + F_vectors[3] +
       F_vectors[2] - F_vectors[0]),
]

IFS_function["dragon"] = [
    lambda z: 0.5 * (1 + 1j) * z,
    lambda z: 1 - 0.5 * (1 - 1j) * z,
]

IFS_function["twin_dragon"] = [
    lambda z: 0.5 * (1 + 1j) * z,
    lambda z: 1 - 0.5 * (1 + 1j) * z,
]

IFS_function["golden_dragon"] = [
    lambda z: R * z * cmath.exp(A * 1j),
    lambda z: R ** 2 * z * cmath.exp((math.pi - B) * 1j) + 1,
]
# z2 dragon curve
IFS_function["z2_dragon"] = [
    lambda z: 0.5 * (1 + 1j) * z,
    lambda z: -(1 - 0.5 * (1 - 1j) * z),
    lambda z: 1 - 0.5 * (1 - 1j) * z,
    lambda z: -(0.5 * (1 + 1j) * z),
]

IFS_function["levy_c"] = [
    lambda z: 0.5 * (1 - 1j) * z,
    lambda z: 1 + 0.5 * (1 + 1j) * (z - 1),
]

IFS_function["z2_levy"] = [
    lambda z: 0.5 * (1 - 1j) * z,
    lambda z: -(1 + 0.5 * (1 + 1j) * (z - 1)),
    lambda z: 1 + 0.5 * (1 + 1j) * (z - 1),
    lambda z: -(0.5 * (1 - 1j) * z),
]

IFS_function["terdragon"] = [
    lambda z: LAMBDA * z,
    lambda z: 1j / math.sqrt(3) * z + LAMBDA,
    lambda z: LAMBDA * z + LAMBDACONJ,
]

IFS_function["z2_golden_dragon"] = [
    lambda z: R * z * cmath.exp(A * 1j),
    lambda z: R * z * cmath.exp((A - math.pi) * 1j),
    lambda z: R ** 2 * z * cmath.exp((math.pi - B) * 1j) + 1,
    lambda z: R ** 2 * z * cmath.exp(-B * 1j) - 1,
]

IFS_function["pentigree"] = [
    _make_func(P_r, vector, offset)
    for vector, offset in zip(P_angle, P_offset)
]

IFS_function["pentadendrite"] = [
    _make_func(Dr, vector, offset) for vector, offset in zip(VVectors, VOffset)
]

# Vars used in koch snowflake
K0 = 0 + 1j
Ka = 0.5 + 0.5 * 1j * math.sqrt(3)
Kna = 0.5 - 0.5 * 1j * math.sqrt(3)
KR = 1 / 3
K_vectors = [1, Ka, Kna, 1]

IFS_function["koch_flake"] = [
    lambda z: KR * (z),
    lambda z: KR * (Ka * z + 1),
    lambda z: KR * (Kna * z + 1 + Ka),
    lambda z: KR * (z + 2),
]

IFS_function["kochawave"] = [
    lambda z: KR * (z),
    lambda z: KR + 1 / math.sqrt(3) * cmath.exp(1j * cmath.pi / 6)*z,
    lambda z: KR + 1 / math.sqrt(3) * cmath.exp(1j * cmath.pi / 6) + KR * cmath.exp(-1j * 2/3 * cmath.pi) * z,
    lambda z: KR * (z + 2)]

DRPR = 1 / (2 + 1 / PHI)

IFS_function["durer_pentagon"] = [
    lambda z: DRPR*z,
    lambda z: DRPR*(1 + z*cmath.exp(2j*cmath.pi/5)),
    lambda z: DRPR*(1 + cmath.exp(2j*cmath.pi/5) + cmath.exp(-2j*cmath.pi/5)*z),
    lambda z: DRPR*(1 + 1/PHI + z)]

R1 = math.sqrt(1/PHI**2 + 1 - 2/PHI*math.cos(3*math.pi/5))
theta1 = math.asin(math.sin(3*math.pi/5)/R1)


