
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARRAY ID\ncalc : obj_list\n     | expression\n     | none\nobj_list : objectobj_list : obj_list objectobject : Name 2D_ARRAYName : IDName : Name ID2D_ARRAY : ARRAY2D_ARRAY : 2D_ARRAY ARRAY\nexpression : ID\n           | ARRAY\n\nnone :\n'
    
_lr_action_items = {'ID':([0,2,5,6,8,9,10,11,12,13,14,],[6,10,-4,-7,12,-5,-7,-6,-8,-9,-10,]),'ARRAY':([0,6,8,10,11,12,13,14,],[7,-7,13,-7,14,-8,-9,-10,]),'$end':([0,1,2,3,4,5,6,7,9,11,13,14,],[-13,0,-1,-2,-3,-4,-11,-12,-5,-6,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'obj_list':([0,],[2,]),'expression':([0,],[3,]),'none':([0,],[4,]),'object':([0,2,],[5,9,]),'Name':([0,2,],[8,8,]),'2D_ARRAY':([8,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> obj_list','calc',1,'p_calc','ifsread.py',80),
  ('calc -> expression','calc',1,'p_calc','ifsread.py',81),
  ('calc -> none','calc',1,'p_calc','ifsread.py',82),
  ('obj_list -> object','obj_list',1,'p_obj_list_1','ifsread.py',93),
  ('obj_list -> obj_list object','obj_list',2,'p_obj_list_2','ifsread.py',98),
  ('object -> Name 2D_ARRAY','object',2,'p_object','ifsread.py',103),
  ('Name -> ID','Name',1,'p_name','ifsread.py',107),
  ('Name -> Name ID','Name',2,'p_name_1','ifsread.py',111),
  ('2D_ARRAY -> ARRAY','2D_ARRAY',1,'p_2D_ARRAY_1','ifsread.py',115),
  ('2D_ARRAY -> 2D_ARRAY ARRAY','2D_ARRAY',2,'p_2D_ARRAY_2','ifsread.py',120),
  ('expression -> ID','expression',1,'p_expression','ifsread.py',126),
  ('expression -> ARRAY','expression',1,'p_expression','ifsread.py',127),
  ('none -> <empty>','none',0,'p_none','ifsread.py',134),
]
