
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARRAY DOCS ID\n    calc : obj_list\n         | expression\n         | none\n     obj_list : object obj_list : obj_list object object : Name 2D_ARRAY object : Name docs 2D_ARRAY Name : ID Name : Name ID docs : DOCS docs : docs DOCS2D_ARRAY : ARRAY2D_ARRAY : 2D_ARRAY ARRAY\n    expression : ID\n               | ARRAY\n               | DOCS\n    \n    none :\n    '
    
_lr_action_items = {'ID':([0,2,5,6,9,10,11,12,14,15,17,18,],[6,11,-4,-8,14,-5,-8,-6,-9,-12,-13,-7,]),'ARRAY':([0,6,9,11,12,13,14,15,16,17,18,19,],[7,-8,15,-8,17,15,-9,-12,-10,-13,17,-11,]),'DOCS':([0,6,9,11,13,14,16,19,],[8,-8,16,-8,19,-9,-10,-11,]),'$end':([0,1,2,3,4,5,6,7,8,10,12,15,17,18,],[-17,0,-1,-2,-3,-4,-14,-15,-16,-5,-6,-12,-13,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'calc':([0,],[1,]),'obj_list':([0,],[2,]),'expression':([0,],[3,]),'none':([0,],[4,]),'object':([0,2,],[5,10,]),'Name':([0,2,],[9,9,]),'2D_ARRAY':([9,13,],[12,18,]),'docs':([9,],[13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> calc","S'",1,None,None,None),
  ('calc -> obj_list','calc',1,'p_calc','ifsread.py',91),
  ('calc -> expression','calc',1,'p_calc','ifsread.py',92),
  ('calc -> none','calc',1,'p_calc','ifsread.py',93),
  ('obj_list -> object','obj_list',1,'p_obj_list_1','ifsread.py',103),
  ('obj_list -> obj_list object','obj_list',2,'p_obj_list_2','ifsread.py',108),
  ('object -> Name 2D_ARRAY','object',2,'p_object','ifsread.py',113),
  ('object -> Name docs 2D_ARRAY','object',3,'p_object_1','ifsread.py',118),
  ('Name -> ID','Name',1,'p_name','ifsread.py',123),
  ('Name -> Name ID','Name',2,'p_name_1','ifsread.py',128),
  ('docs -> DOCS','docs',1,'p_docs','ifsread.py',134),
  ('docs -> docs DOCS','docs',2,'p_docs_1','ifsread.py',139),
  ('2D_ARRAY -> ARRAY','2D_ARRAY',1,'p_2D_ARRAY_1','ifsread.py',144),
  ('2D_ARRAY -> 2D_ARRAY ARRAY','2D_ARRAY',2,'p_2D_ARRAY_2','ifsread.py',149),
  ('expression -> ID','expression',1,'p_expression','ifsread.py',155),
  ('expression -> ARRAY','expression',1,'p_expression','ifsread.py',156),
  ('expression -> DOCS','expression',1,'p_expression','ifsread.py',157),
  ('none -> <empty>','none',0,'p_none','ifsread.py',164),
]
